name: Build and Deploy to Wasmer

on:
  push:
    branches:
      - main  # change to master if your default branch is master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Wasmer CLI
        uses: wasmerio/setup-wasmer@v1

      - name: Deploy to Wasmer
        run: wasmer deploy --app-name lumios-test --owner candleflamegh
        env:
          WASMER_TOKEN: ${{ secrets.WASMER_TOKEN }}
